import { Exercise } from './types';
import { generateId } from './utils';
import { getDB } from './storage/indexedDB';

export const popularExercises: Exercise[] = [
  // CHEST EXERCISES
  {
    id: generateId(),
    name: 'Bench Press',
    muscleGroup: 'chest',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 180,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Incline Bench Press',
    muscleGroup: 'chest',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 180,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Chest Press',
    muscleGroup: 'chest',
    type: 'dumbbell',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    type: 'dumbbell',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Flyes',
    muscleGroup: 'chest',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Push-ups',
    muscleGroup: 'chest',
    type: 'bodyweight',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dips',
    muscleGroup: 'chest',
    type: 'bodyweight',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },

  // BACK EXERCISES
  {
    id: generateId(),
    name: 'Deadlift',
    muscleGroup: 'back',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 300,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Pull-ups',
    muscleGroup: 'back',
    type: 'bodyweight',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Barbell Rows',
    muscleGroup: 'back',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 150,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'T-Bar Rows',
    muscleGroup: 'back',
    type: 'machine',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Lat Pulldowns',
    muscleGroup: 'back',
    type: 'cable',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Seated Cable Rows',
    muscleGroup: 'back',
    type: 'cable',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Rows',
    muscleGroup: 'back',
    type: 'dumbbell',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Chin-ups',
    muscleGroup: 'back',
    type: 'bodyweight',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },

  // LEG EXERCISES
  {
    id: generateId(),
    name: 'Squats',
    muscleGroup: 'legs',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 180,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Romanian Deadlift',
    muscleGroup: 'legs',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 180,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Bulgarian Split Squats',
    muscleGroup: 'legs',
    type: 'dumbbell',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Leg Press',
    muscleGroup: 'legs',
    type: 'machine',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Lunges',
    muscleGroup: 'legs',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Leg Curls',
    muscleGroup: 'legs',
    type: 'machine',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Leg Extensions',
    muscleGroup: 'legs',
    type: 'machine',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Calf Raises',
    muscleGroup: 'legs',
    type: 'machine',
    defaultRestTime: 60,
    created: new Date(),
    lastUsed: new Date(),
  },

  // SHOULDER EXERCISES
  {
    id: generateId(),
    name: 'Overhead Press',
    muscleGroup: 'shoulders',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 150,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    type: 'dumbbell',
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Rear Delt Flyes',
    muscleGroup: 'shoulders',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Upright Rows',
    muscleGroup: 'shoulders',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Face Pulls',
    muscleGroup: 'shoulders',
    type: 'cable',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },

  // ARM EXERCISES
  {
    id: generateId(),
    name: 'Barbell Curls',
    muscleGroup: 'arms',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Curls',
    muscleGroup: 'arms',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Hammer Curls',
    muscleGroup: 'arms',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Tricep Dips',
    muscleGroup: 'arms',
    type: 'bodyweight',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Close-Grip Bench Press',
    muscleGroup: 'arms',
    type: 'barbell',
    barWeight: 45,
    defaultRestTime: 120,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Tricep Extensions',
    muscleGroup: 'arms',
    type: 'dumbbell',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Cable Curls',
    muscleGroup: 'arms',
    type: 'cable',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
  {
    id: generateId(),
    name: 'Cable Tricep Pushdowns',
    muscleGroup: 'arms',
    type: 'cable',
    defaultRestTime: 90,
    created: new Date(),
    lastUsed: new Date(),
  },
];

export async function seedPopularExercises() {
  try {
    const db = await getDB();
    
    // Check if exercises already exist
    const existingExercises = await db.getExercises();
    if (existingExercises.length > 0) {
      console.log('Exercises already exist, skipping popular exercises seed');
      return;
    }
    
    // Add popular exercises
    for (const exercise of popularExercises) {
      await db.createExercise(exercise);
    }
    
    console.log(`Seeded ${popularExercises.length} popular exercises!`);
  } catch (error) {
    console.error('Failed to seed popular exercises:', error);
  }
}